version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dweduqbr
      POSTGRES_PASSWORD: WZK6s9mL-vfOznC-U4PUWyr1NYPTkjPn
      POSTGRES_DB: dweduqbr
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://dweduqbr:WZK6s9mL-vfOznC-U4PUWyr1NYPTkjPn@trumpet.db.elephantsql.com/dweduqbr
    ports:
      - "5000:5000"
